services:
  postgres:
    image: postgres:16
    container_name: trello_clone_postgres
    restart: always

    environment:
      POSTGRES_USER: trello_user
      POSTGRES_PASSWORD: trello_password
      POSTGRES_DB: trello_clone

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: